# Automatic trigger disabled
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deployment step"
